### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "asdf@asdf.com",
  "password": "asdfasdf"
}

### Sign in a new user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "asdf@asdf.com",
  "password": "asdfasdf"
}

### Find a user with given ID
GET http://localhost:3000/auth/1


### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com


### Delete a give user with id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/1
content-type: application/json

{
  "email": "ccc@ccc.com"
}
